train: ./train/data
val: ./validation/data 
nc: 9                   
names: [
    'vehicle', 
    'pedestrian', 
    'traffic-sign', 
    'traffic-light-green',
    'traffic-light-red',
    'traffic-light-etc',
    'crosswalk',
    'two-wheeled-vehicle',
    'bike'
    ]